PACKAGE_NAME="amd-xgbe-asustor"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="amd-xgbe"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/updates"
DEST_MODULE_NAME[0]="amd-xgbe"

MAKE[0]="make -C src KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C src KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
